export const DOM_IDS = {
  app: 'app',
  shell: 'shell',
  breadcrumb: 'breadcrumb',
  uploadDrop: 'uploadDrop',
  fileInput: 'fileInput',
  fileList: 'fileList',
  uploadMeta: 'uploadMeta',
  previewModal: 'previewModal',
  previewTitle: 'previewTitle',
  previewBody: 'previewBody',
  previewClose: 'previewClose',
  collapseRight: 'collapseRight',
  expandRight: 'expandRight',
  historyMenu: 'historyMenu',
  historyList: 'historyList',
  themeToggle: 'themeToggle',
  themeToggleText: 'themeToggleText',
  backToTop: 'backToTop',
  settingsToggle: 'settingsToggle',
  settingsModal: 'settingsModal',
  settingsClose: 'settingsClose',
  formalReport: 'formalReport',
  shareReport: 'shareReport',
  sharePanel: 'sharePanel',
  shareLink: 'shareLink',
  copyShareLink: 'copyShareLink',
  downloadReport: 'downloadReport',
  downloadMenu: 'downloadMenu',
  downloadPdf: 'downloadPdf',
  downloadMarkdown: 'downloadMarkdown',
};

export const ACTIONS = {
  renameHistory: 'rename',
  viewHistory: 'view',
  deleteHistory: 'delete',
};
